docs/fast_data/configuration/single_view_creator/common.md

Removed required check for KAFKA_GROUP_ID in the single view creator

fix: KAFKA_GROUP_ID env var is not required for svc

---

docs/fast_data/configuration/realtime_updater/common.md
docs/fast_data/inputs_and_outputs.md

In this page: [Inputs and Outputs | Mia-Platform Documentation](https://docs.mia-platform.eu/docs/fast_data/inputs_and_outputs)  the documentation refers to an ingestion message where the `value` property does not contain the key.
The documentation page has been updated to include also the key values in the `value` field.
This behaviour has also been properly stated on the RTU page.

Fix (FDBM-63): Update DB2 Message Adapter: Specify Key in value Field for Ingestion Messages

---

docs/fast_data/configuration/single_view_trigger_generator.md

Single View trigger generator configmap eventStoreConfig kafka's brokers are a string not an array of strings

refactor(): SVTG eventStoreConfig kafka brokers are string not array of string

---

docs/fast_data/bucket_storage_support/configuration/ingestion_storer.md

Introduce new Ingestion Storer configuration parameter, `bucket-folder`, which allows to customize for each ingestion topic in which folder its messages are stored.

docs(bss): add bucket-folder configuration to ingestion-storer

---

docs/fast_data/configuration/single_view_trigger_generator.md

Kafka's log level in the SVTG is a string not a number anymore

fix(): kafka log level is string not number in SVTG

---

docs/fast_data/monitoring/dashboards/single_views.md

- The monitoring section of the Fast Data mentions the need to enabling the "gather metrics" flag in console for the interested services
- Mention the SVTG in the metrics available

feat(fast-data): monitoring mentions enabling metrics flag in console

---

docs/fast_data/configuration/config_maps/aggregation.md

This PR has the goal of adding a warning paragraph inside the No Code Aggregation section to advice not to use JSON Schema operators inside the Aggregation config map, since this type of operators are not handled by the No Code.

fix(FDCBM-18): Added warning for Aggregation No Code

---

docs/fast_data/inputs_and_outputs.md

Deprecated I/O messages of fast data:
- kafka-projection-changes
- sv-before-after
- svc-events

feat(fast-data): deprecate old I/O messages

---

docs/fast_data/configuration/single_view_creator.md
docs/fast_data/single_view_trigger_generator.md

Add missing steps on the configuration of the sv-patch in the Single View Creator

fix(fast-data): add missing steps to configure sv-patch on the svc

---

docs/release-notes/v11.7.0.md

This PR to the release-note provide a notification that an issue has arise in the Fast Data Configurator, which prevents to deploy the project after saving a change on the Console project.

docs(release-note): add notice of impacting issue due to fd configurator release

---

docs/fast_data/configuration/realtime_updater.md

Inform the user that two pr-update messages are generated when there's the update of a primary key

fix(fast-data): Two Projection Update messages sent when Primary Key update

---

docs/fast_data/configuration/config_maps/projection_changes_schema.md

This PR adds a section `Custom Functions` in the `Projection Changes Schema` config map where is stated the location in which custom functions should be placed

Enhance custom functions section in the pc schema configuration

---

docs/fast_data/inputs_and_outputs.md

As described in the title, in the Fast Data input output page it has been added a new paragraph that explains the different versions of SV Update event, which is emitted by Single View Creator service.

docs(fast-data): introduce sv-update v2 specification in input-output page

---

.cspell.json

This PR will add the [logr](https://github.com/go-logr/logr/) library to the ignored words for cspell.
Is necessary because miactl is using that library and we recently updated it so its name is inside the CHANGELOG and cspell is blocking the PR for integrating the new version.

Add logr library name to ingored words for cspell

---

docs/fast_data/configuration/config_maps/aggregation.md

In this PR are added two banner at the start and at the end of the  `_select` paragraph, in the aggregation advanced features section. In this manner users are aware of feature state and should be discouraged from using it.

docs(fast-data): deprecate use of _select aggregation advanced feature

---

.cspell.json

In the Mia Care P4SaMD Node.js template documentation we reference [Fluentd](https://www.fluentd.org/), but the name is not recognized as a valid word by cspell, causing the build to fail. This PR add the `Fluentd` word to cspell.

Add Fluentd to cspell

---

docs/fast_data/configuration/indexes.md

After [discussion 502](https://github.com/mia-platform/community/discussions/502), we found out that two automatic indexes generated by Mia Console for fast data are not needed if Projection Storer is used.
This PR addresses this use case by specifying that those indexes are not needed when a Projection Storer has been employed

update: fast data indexes section

---

.cspell.json

SaMD (Software as Medical Device) is not recognized as a valid word by cspell, causing the build of the Mia Care Node.js template documentation to fail. This PR add the SaMD word to cspell.

Add SaMD to cspell

---

.cspell.json

Add `pkce` to excluded words in cspell.json

Add pkce to cspell

---

docs/fast_data/configuration/config_maps/kafka_projection_updates.mdx

Add visualization of the update event object structure for manual strategies and the reason it has such shape

fix(fast-data): add update event structure view in kafka projection updates

---

docs/fast_data/configuration/projection_storer.md
docs/fast_data/faq/fast_data_versioning.md

In this PR is clarified a bug encountered with the execution of `castToDate` cast function over Unix timestamps and which version of the service should be upgraded it.

docs(fast-data): add notice of projection-storer bug

---

docs/data_catalog/compatibility_matrix.md
docs/data_catalog/data_catalog_fabric_bff.mdx
docs/fast_data/faq/fast_data_versioning.md
docs/fast_data/runtime_management/compatibility_matrix.md
static/schemas/data_fabric/data-catalog-fabric-bff.config.schema.json

Version 0.2.1 of Fabric BFF supports custom x509 certificates when reaching upstream services.
- Application config schema updated
- Compatibility matrix + latest versions updated

add(data-catalog): add documentation for TLS custom certificate support on fabric BFF

---

docs/console/company-configuration/providers/configure-provider.mdx

Added more details on how to configure the field **Repo path template** for different git providers on provider configuration.

Improved documentation on Git Provider documentation

---

docs/console/tutorials/visualize-infrastructure-project-components-runtime-data-in-console.md
docs/software-catalog/items-management/miactl.md
docs/software-catalog/tutorials/service-template-integrated-with-jenkins.md
docs/software-catalog/tutorials/software-catalog.md

Changed `miactl marketplace` commands in software catalog doc and tutorial to the new `miactl catalog` command

fix(sofware caralog): miactl commands
