docs/development_suite/company/create.mdx
docs/development_suite/set-up-infrastructure/create-project.mdx

feat: docker image pull secrets docs

---

docs/development_suite/console-levels-and-permission-management.md

feat(JCE-459): new permissions for superuser

---

docs/release-notes/platform_10-5-1_releasenotes.md

fix anchor

---

docs/fast_data/configuration/single_views.md

This PR has the goal of expanding documentations about the Fast Data Low Code Test Template repository and its use when testing Low Code configurations.

feat(FDE-557): Added 'How to test Low Code configurations' inside Single Views configurations page

---

docs/tutorial/console/console_handbook.md
docs/tutorial/console/project_handbook.md
sidebars.json

"Getting started" pages structure reviewed

Getting started structure modified

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Update CONTRIBUTING links

---

docs/fast_data/configuration/config_maps/erSchema.md

This PR is for adding the beta banner in the ER Schema no code section.
This PR is for adding the beta banner in the ER Schema no code section to let the user know that it is still a beta feature.

added beta banner to no code

---

docs/development_suite/api-console/api-design/endpoints.md

- [] Documentation content changes
this PR fix the documentation following the input given in this discussion: https://github.com/mia-platform/community/discussions/217

fix examples for user group permission in endpoint documentation

---

docs/development_suite/identity-and-access-management/service-account-management.md
docs/development_suite/identity-and-access-management/user-management.md

Fix: improve image positioning in Identities docs

---

301redirects.json

Fixed some formal errors on the redirect file

fix wrong redirects

---

docs/fast_data/configuration/config_maps/erSchema.md

The ER Schema presented as example in the `erSchema.md` page has been updated with a working ER Schema that reflects the structure in the image attached next to it and that it works in the ER Schema No Code canvas.

fix: updated example of ER Schema

---

package.json
src/theme/SearchBar/index.js
yarn.lock

React moved to 17 since docusaurus does not support React 18.
Fix SearcBar theme component

fix: search

---

docs/development_suite/user-settings/feature-preview.md

Update feature-preview.md image

---

docs/release-notes/platform_10-7-0_releasenotes.md

Editing helm chart version for RN 10.7.0

---

.cspell.json

- Adding dicom, qido, wado cspell exceptions

[Doc] DICOM Service cspell exceptions

---

docs/release-notes/platform_10-7-1_releasenotes.md
docs/release-notes/versions.md
sidebars.json

add RN 10.7.1

---

.cspell.json
docs/fast_data/connectors/debezium_cdc.md

Add documentation for the new PostgreSQL Debezium connector plugin available in the marketplace

PostgreSQL Debezium connector plugin documentation

---

docs/fast_data/connectors/overview.md

Several minor improvements on Fast Data section.

Several minor improvements on Fast Data section 

---

301redirects.json

Add missing redirection link after merging the new miactl documentation location

Add miactl redirects

---

docs/development_suite/identity-and-access-management/service-account-management.md

Removing the Service Account `audience` from the auth example in the Service Account authentication section. The Console does not support it and therefore it is misleading for users.

remove audience from service account example

---

CONTRIBUTING.md

chore: fix repository URL in CONTRIBUTING

---

docs/fast_data/connectors/debezium_cdc.md

feat(FDICDC-49): Add Debezium Server Generic Template docs

---

docs/fast_data/monitoring/dashboards/consumer_groups.md
docs/fast_data/monitoring/dashboards/projection_changes.md
docs/fast_data/monitoring/dashboards/single_views.md
docs/fast_data/monitoring/dashboards/unmapped_fields.md
docs/fast_data/troubleshooting/rtu_keeps_restarting_rebalancing.md

Including some updates for better clarity in _Monitoring_ and _Troubleshooting_ sections in Fast Data documentation.

docs(fast-data): review monitoring and troubleshooting sections

---

docs/fast_data/configuration/realtime_updater/common.md
docs/fast_data/configuration/realtime_updater/low_code.md
docs/fast_data/realtime_updater.md

docs(fast-data): review real-time-updater documentation

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md

Editing Console levels permissions

---

301redirects.json

This PR fixes the missing redirect for the Data Organizer page that it has been removed from the documentation.

fix(bss): add data organizer page to redirects list

---

301redirects.json

fix: Redirect for broken links of Fast Data CSV Connector

---

.cspell.json
docs/tutorial/node_ms/node_ms_tutorial.mdx
docusaurus.config.js

Updated the `create microservice` tutorial with c# .NET example

Custom mircroservice tutorial dotnet version

---

docs/development_suite/identity-and-access-management/service-account-management.md

This PR introduces some improvements on Service Account login with `private_key_jwt` flow

fix: improve private key jwt docs for console login with m2m

---

docs/release-notes/v11.0.0.md

feat: update release note v11 with Fast Data updates

---

docs/release-notes/mia-platform-v11.mdx
docs/release-notes/v11.0.0.md

overview_v11 typos fix

---

docs/development_suite/company/project-templates.md

edit: improved "default services" section in "project templates" doc

---

docs/release-notes/v11.0.0.md

fix chart helm version v11.0.0

---

docs/release-notes/v11.0.1.md
docs/release-notes/versions.md
sidebars.json

RN v11.0.1

---

docs/release-notes/v11.0.2.md
docs/release-notes/versions.md
sidebars.json

RN_v11.0.2

---

docs/release-notes/versions.md
sidebars.json

re-ordering RN console versions

---

sidebars.json

reorder fast data sidebar

---

.github/workflows/build.yml

Fix: Fixed cache key to save node-modules on github actions

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md
docs/marketplace/add_to_marketplace/contributing_overview.md

project: private marketplace docs

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md
docs/marketplace/add_to_marketplace/contributing_overview.md

Private Marketplace docs improvements

---

package.json
yarn.lock

This PR contains some dependencies upgrades

upgrade depedencies

---

sidebars.json

changed group position in sidebar

---

301redirects.json
docs/development_suite/api-console/api-design/overview.md
sidebars.json
versioned_docs/version-9.x.x/fast_data/configuration/single_views.md

added redirect design docs

---

301redirects.json

fix: api-design overview page redirect

---

docs/development_suite/identity-and-access-management/service-account-management.md

Add article ref in m2m docs

---

docs/runtime_suite/user-manager-service/20_configuration.md
docs/runtime_suite/user-manager-service/30_usage.md
docs/runtime_suite/user-manager-service/changelog.md

chore(docs): update User Manager Service documentation

chore(docs): update User Manager Service documentation

---

docs/release-notes/v11.1.1.md
docs/release-notes/versions.md
sidebars.json

New RN v11.1.1

---

docs/development_suite/api-console/api-design/crud_advanced.md

Minor fix on one of the examples included related to the configuration of JOSN Schema to be used in CRUD Service. The suggested keyword `example` has been replaced by `examples` and its value has been changed to an array.

fix: update the Valid Schema example to have "examples" property

---

docs/self_hosted/self_hosted_requirements.md

Azure AD B2C added as auth provider

---

docs/fast_data/bucket_storage_support/configuration/bucket_connection.md

In this PR it is introduced a simple warning in the Bucket Storage Support configuration page, in particular the one regarding the bucket configuration. This warning should help users to solve a potential startup issue that may be encountered while configuring the service for the first time.

docs(bss): improve configuration description

---

.cspell.json
docs/how_to/traefik/traefik_handbook.mdx
sidebars.json

add documentation for add basic auth with traefik

---

.cspell.json
docs/fast_data/bucket_storage_support/configuration/ingestion_reloader.md

Fdhd 101 selective reingestion

---

nginx/website.conf

Add YouTube domain to the CSP inside nginx config

add youtube to the CSP

---

docs/fast_data/inputs_and_outputs.md

General refactor of the Inputs and Outputs page of the fast-data.
Corrected the asyncapi specifications as well as the examples.

refactor(): Refactor of the Inputs and Outputs page

---

docs/development_suite/api-console/api-design/authorization.md

Authorization management page: add reference to Rönd route-specific options

---

docs/business_suite/backoffice/60_components/60_data_visualization.md

- [X ] Documentation content changes

fix atlas dashboard format and typo

---

docs/paas/docker-registry.md
sidebars.json

Adding the section for Nexus on PaaS, describing our cleanup policies.

feat: add paas/docker-registry section

---

docs/development_suite/set-up-infrastructure/remove-environment.md

I added a link, in the "Delete an Environment" page, pointing to the section with the documentation about the environment deletion from the console.

Delete environment improvement

---

docs/marketplace/add_to_marketplace/contributing_overview.md
docs/release-notes/v11.1.0.md

edit private marketplace docs

---

docs/runtime_suite/function-service/configuration.md

I just changed the HTTP Verb of the example file of the function service from `POST` to `GET`.
A user expects a hello-world route in GET, not in POST (I lost time figuring out why the route wasn't working, I was just using the wrong verb :/ ).

Change function service example

---

301redirects.json
docs/business_suite/backoffice-configurator/30_compose-pages.md
docs/business_suite/backoffice-configurator/40_configurator-settings.md
docs/business_suite/backoffice-configurator/60_external-components/10_overview.md

Mapped the redirect for renamed page in Backoffice Configurator documentation, and fixed some sidebar labels.

Mapped Backoffice Configuration redirect

---

docs/development_suite/overview-dev-suite.md

edit: What's new section description in Console Overview

---

docs/release-notes/v11.0.0.md
docs/release-notes/v11.0.1.md
docs/release-notes/v11.0.2.md
docs/release-notes/v11.1.0.md
docs/release-notes/v11.1.1.md
docs/release-notes/v11.1.2.md
docs/release-notes/v11.2.0.md
docs/release-notes/v11.2.1.md
docs/release-notes/v11.3.0.md

feat: link to self hosted guide

---

301redirects.json

Added missing 301 redirects for backoffice configurator doc

Added redirectes

---

docs/release-notes/v11.4.2.md
docs/release-notes/versions.md
sidebars.json

RN v11.4.2

---

301redirects.json
package.json

add new redirect

---

docs/fast_data/bucket_storage_support/configuration/ingestion_storer.md

Updates to Ingestion Storer service (Fast Data/BSS) including:
- v1.5.0 new env vars
- fixed json schemas for events/payloads
- added section on cluster fine tuning

chore(docs): update Fast-Data/BSS/Ingestion Storer

---

docs/development_suite/user-settings/user-preferences.md
docs/development_suite/user-settings/user-profile-picture.md

edit User settings sections

---

docs/development_suite/identity-and-access-management/manage-groups.md

Rewrite manage groups docs to improve clearness and readability.

*update manage groups page

---

docs/fast_data/inputs_and_outputs.md

Fix PR update schema in inputs and ouputs

fix(fast-data): pr-update schema fix

---

docs/fast_data/configuration/indexes.md

Add paragraph for Single View Errors collections in indexes page.

feat(fast-data): Add sv-errors paragraph in indexes page

---

docs/development_suite/set-up-infrastructure/enhanced-project-workflow.md

Enhanced Project Workflow documentation fix

---

docs/development_suite/set-up-infrastructure/enhanced-project-workflow.md

fix typos enhanced project docs

---

301redirects.json
versioned_docs/version-9.x.x/development_suite/set-up-infrastructure/create-project.mdx

fix some doc redirects

---

docs/marketplace/add_to_marketplace/marketplace_items_accessibility.md

chore: typo

---

docs/development_suite/monitoring/resources/cronjobs.md

chore: fix typo on CronJobs runtime page

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md

chore(docs): update console levels and permissions

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md

delete version permission docs

---

docusaurus.config.js

Some links in the footer were outdated or redirected, so I updated them.

Updated footer links

---

docs/development_suite/api-console/api-design/microservice-runtime-resources.md

Modified the `Microservice Runtime Resources` section to specify the probes port behavior.

feat: added probes port section

---

301redirects.json

Update and add some redirects.

update and add redirects

---

src/pages/index.js

Fix broken link in the home page

update homepage links

---

docs/business_suite/backoffice/changelog.md

Update changelog of Backoffice components library (`back-kit`)

Edit: Update back-kit changelog

---

301redirects.json

update broken links

---

docs/release-notes/roadmap.md

Update Roadmap page, changed future work section.

*update roadmap page

---

CONTRIBUTING.md

chore: explain actions to do when deleting a page

---

docs/marketplace/add_to_marketplace/contributing_overview.md

add specification of how service id must be written

---

docs/development_suite/api-console/api-design/microservice-monitoring.md

update enable metrics card description

---

docs/getting-started/tutorials/backoffice/auth0-integration.mdx

update wrong internal links

---

docs/release-notes/v11.5.3.md
docs/release-notes/versions.md
sidebars.json

update: 11.5.3

---

docs/infrastructure/private-clusters.mdx

Remove TL;DR; and fix warning message

[Private clusters] Remove TL;DR; and fix warning message

---

docs/release-notes/v11.7.0.md
docs/release-notes/v11.7.1.md
docs/release-notes/versions.md
sidebars.json

Release note/v11.7.1

---

docs/getting-started/tutorials/fast-data/low-code.mdx

Updated Fast Data Low Code tutorial to handle date fields in nested CRUD schema definition

*upd fastdata tutorial

---

docs/fast_data/configuration/single_view_trigger_generator.md

In this PR is reviewed the configuration page of Single View Trigger Generator with respect to the version `v3.0.4`. In particular:
- unused environment variables were 
- `ssl` description in Kafka consumer and producer configuration (in the event store) has been expanded to contains details regarding how to load certificates and keys

docs(fast-data): review configuration schema of single-view-trigger-generator

---

docs/info/version_policy.md

Updated version policy with estimated EOL for v10 and v11

update: version policy with EOL for v10 and v11

---

.github/workflows/build.yml

This PR addresses a OOM problem during build

fix: Node OOM during build stages of pipeline

---

docs/fast_data/configuration/projection_storer.md

Clarify how Real-Time Updater and Projection Storer can share custom functions.

docs(fast-data): add explanation for sharing custom functions between different services

---

src/components/VersionBanner/styles.module.css
src/pages/index.js

Update Doc HomePage with links for v12

update doc homepage - v12 banner and links

---

301redirects.json

Update redirects about backoffice tutorials

update backoffice redirects

---

docs/marketplace/add_to_marketplace/contributing_overview.md
versioned_docs/version-11.x.x/marketplace/add_to_marketplace/contributing_overview.md

add how to set defaultLabels on marketplace item

---

docs/release-notes/mia-platform-v12.mdx
docs/release-notes/v12.0.0.md

RN-v12-final-fixes

---

docs/release-notes/v12.0.0.md

edit miactl rn

---

docusaurus.config.js

Remove preview banner to the v12 doc

remove preview banner

---

docs/release-notes/mia-platform-v12.mdx
docs/release-notes/v12.0.0.md

docs v12 small adjustments

---

docusaurus.config.js

Updated blog URL in the footer

---

docs/fast_data/configuration/realtime_updater.md
docs/fast_data/configuration/single_view_trigger_generator.md

The real time updater and single view trigger configuration pages now contains a tip panel to show how er schema config maps can be shared

DEVDOC-145: Add tips about shared er schema

---

docs/development_suite/api-console/advanced-section/api-gateway-envoy/extensions.md
docs/development_suite/api-console/advanced-section/api-gateway-envoy/jwt-authn.md

THe authentication use case of Envoy advance configuration has been enhanced with tips, warnings, and a re-organized structure, to explain different functionalities offered by the jwt filter (cookies, multi-auth, etc...)

DEVDOC220: Update jwt authn section

---

.github/labeler.yml

Automatically add labels to PRs, so that reviewers have an easier time in navigating the ones they should be interested in.
This PR introduce a configuration that trigger a Github feature for automatically adding labels on PRs, depending on which files have been modified within the PR.
The feature is describe here: https://github.com/actions/labeler

ci(github): add labeler config to automatically label pull-requests

---

docs/fast_data/connectors/overview.md

Specify that Fast Data needs the full record on ingestion

fix(fast-data): Specify that Fast Data needs the full record on ingestion

---

301redirects.json
docs/marketplace/compatibility_matrices/mongo_compatibility_matrix.md
sidebars.json
versioned_docs/version-9.x.x/marketplace/compatibility_matrices/mongo_compatibility_matrix.md

feat: restore marketplace compatibility matrix

---

docs/release-notes/mia-platform-v12.mdx
docs/release-notes/v12.0.0.md

RN v12 Adjustments for Prod release

---

301redirects.json

Restore link redirects to the v12 pages.
**WARNING** to merge on 30th Nov.

add redirects to the v12 features, pages and other

---

src/components/LastPages/index.js

use custom groupBy function istead of Object.groupBy to fix error in build pipeline

use custom groupBy function istead of Object.groupBy

---

301redirects.json

fix SLA agreement page redirect

sla agreement redirect

---

docs/marketplace/add_to_marketplace/manage_marketplace_items.md

fix: remove duplicated tenantId from a marketplace item example

---

301redirects.json

fix redirects

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md

Updated mia-platform role permissions table

---

docs/release-notes/v12.0.0.md
docs/release-notes/v12.0.1.md
docs/release-notes/versions.md
sidebars.json

RN v12.0.1 - docs preview

---

docs/release-notes/v12.0.1.md

fix(Fast Data): adding missing fix in v12.0.1 release notes

---

docs/release-notes/v12.0.1.md

edit chart helm version RN v12.0.1

---

docs/console/project-configuration/kustomize-your-configurations/kustomize-use-cases.md
docs/runtime_suite/real-time-updater/changelog.md

Kustomize Use Cases: add some info to better improve the readness of the page

---

docs/fast_data/configuration/projection_storer.md
docs/fast_data/faq/fast_data_versioning.md

In this PR are updated the example of custom message adapters that can be employed in the Projection Storer

docs(fast-data): review projection storer custom message adapter

---

docs/release-notes/v12.0.1.md

edit RN v12.0.1 for prod release

---

301redirects.json

Links redirects are added for renamed back-kit pages.

Add link redirects for renamed pages

---

docs/release-notes/v12.0.0.md
docs/release-notes/v12.0.2.md
docs/release-notes/versions.md
sidebars.json

RN v12.0.2

---

.github/dependabot.yml

In this PR is introduced a Dependabot [configuration](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) which allows to group packages updates together according to specific patterns.
In this manner, Dependabot would open a single PR for the group, rather than creating one for each package that has to be updated.

ci(dependabot): add groups configuration

---

.github/labeler.yml
.github/workflows/labeler.yml

Update `labeler` config to v5 and add workflow to actually run it.

ci(labeler): add workflow to run labeler

---

docs/getting-started/mia-platform-overview.md
src/pages/index.js

Move useful resources from getting started to homepage

Move useful resources from getting started to homepage

---

docs/runtime_suite_applications/api-documentation-aggregator/overview.md

edit API documentation aggregator docs

---

docs/release-notes/stable versions.md
sidebars.json

Stable versions docs page

---

docs/release-notes/v12.0.2.md

RNv12.0.2 for prod release

---

docs/release-notes/v12.1.0.md

Mia care R&D updates

---

docs/development_suite/monitoring/resources/jobs.md

edit: explain deletion policy used for jobs deletion

---

docs/release-notes/v12.0.2.md

Updated RN with merge modal fix

---

docs/infrastructure/paas/secret-scanning.md

edit: fix keyword for ignoring dummy secrets with inline comments

---

301redirects.json

Fixed wrong redirect on /docs/getting-started/guidelines/

*fixed guidelines redirect

---

docs/marketplace/compatibility_matrices/mongo_compatibility_matrix.md

Update the `compatibility matrix` page for MongoDB on the `marketplace` section

chore(marketplace): update mongodb compatibility matrix on fast-data

---

docs/console/project-configuration/project-settings.md
docs/development_suite/set-up-infrastructure/enhanced-project-workflow.md
docs/release-notes/mia-platform-v12.mdx

This PR introduces improvements to the Enhanced Project Workflow documentation page by showcasing its benefits.

feat: enhanced project workflow benefits and improved beta message

---

docs/release-notes/v12.1.0.md

Edit v12.1.0 for prod release

---

docs/development_suite/set-up-infrastructure/enhanced-project-workflow.md

This PR includes best practices for revision management when using the Enhanced Project Workflow

docs: enhanced workflow best practices for revision management

---

docs/development_suite/company/create.md

feat: remove warn message

---

docs/release-notes/v12.2.0.md

RN v12.2.0 to prod

---

docs/development_suite/api-console/advanced-section/api-console-configuration.md
versioned_docs/version-11.x.x/development_suite/api-console/advanced-section/api-console-configuration.md

Add documentation example to the advanced api console configuration page.

Improve advanced api-console-config - Add custom envs example

---

docs/marketplace/overview_marketplace.md

Added Marketplace contribuition ref to Marketplace overview page

---

docs/getting-started/faqs.md

add test for new workflow

---

docs/release-notes/v12.2.1.md

RN v12.2.1 to prod

---

docs/development_suite/company/create.md
docs/development_suite/company/project-templates.md
docs/infrastructure/self-hosted/installation-chart/80-first-user-and-company-creation.md

Improvements to CMS related pages

---

docs/fast_data/configuration/import_export.md

import/export FD docs improvement

---

docs/info/bug_policy.md

Removed old section related to report a bug, no longer valid

removed old process section

---

docs/marketplace/add_to_marketplace/manage_marketplace_items.md

Updated delete command in documentation

Updated Delete command in documentation

---

.cspell.json
docs/marketplace/add_to_marketplace/contributing_overview.md

I added a template to create a mia platform starter from code and added the list of marketplace categories

Added "Start with code" template and the list of categories

---

docs/development_suite/set-up-infrastructure/enhanced-project-workflow.md

Added helpful documentation on Secrets management on Enhanced Project Workflow

edit: secret variables management on enhanced workflow

---

docs/console/company-configuration/providers/configure-provider.mdx
docs/console/project-configuration/create-a-project.mdx

feat: repository path template

---

docs/fast_data/tutorials/low-code.mdx

fix: fast data tutorial kafka envs

---

docs/release-notes/v12.0.3.md
docs/release-notes/versions.md
sidebars.json

RN v12.0.3

---

docs/release-notes/v12.0.3.md

Update the release note of the v12.0.3 of the Console to include the Fast Data hotfix included

fix: RN v12.0.3 to include Fast Data hotfix

---

src/pages/index.js

doc banner for new navigation

---

docs/release-notes/v12.0.3.md

Removing empty paragraph in v12.0.3 release note, to avoid confusion.

fix: removed empty paragpraph

---

README.md
docs/getting-started/mia-platform-overview.md
src/pages/index.js

I have updated some links to Mia-Platform Website

Updated some links

---

docs/release-notes/v12.3.0.md
docs/release-notes/v12.3.1.md
docs/release-notes/versions.md
sidebars.json
src/pages/index.js

RN 12.3.1 to Preview

---

docs/release-notes/versions.md

fix: rn version table

---

docs/development_suite/company/create.md

I fixed example call for Company creation API since body was missing.

fix: example call for create company api was missing

---

docs/release-notes/v12.3.1.md

RN v12.3.1 to prod release

---

301redirects.json

edit 301redirects

---

docusaurus.config.js
static/robots.txt

I added the robots.txt file that was missing, giving it instructions to ignore old versions. I also edited the config for the sitemap, ignoring the same old versions. This should solve some SEO issues, because old versions of the docs are now considered duplicate content.

Added robots.txt and other edits for SEO reasons

---

docs/release-notes/v12.3.2.md
docs/release-notes/versions.md
sidebars.json

RN v12.3.2

---

docs/release-notes/v12.0.3.md

Add info on v12.0.3

---

docs/release-notes/v12.0.3.md
docs/release-notes/v12.3.2.md
docs/release-notes/versions.md
sidebars.json

Edit/release v12.3.2 to prod

---

docs/release-notes/v12.4.0.md

edit RN v12.4.0 for prod release

---

docs/console/company-configuration/providers/extensions/orchestrator-generator/overview.mdx

update: doc for configurationRef in custom orchestrator generator docs

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md

feat: new permission console.root.all.view

---

docs/microfrontend-composer/previous-tools/cms/colorare_il_cms.md
docs/microfrontend-composer/previous-tools/cms/conf_cms.md
docs/microfrontend-composer/previous-tools/cms/config_cms.md
docs/microfrontend-composer/previous-tools/cms/custom-frontends-integration-CMS.md
docs/microfrontend-composer/previous-tools/cms/guide_cms.md
docs/microfrontend-composer/previous-tools/cms/update_cms.md
docs/microfrontend-composer/previous-tools/cms/video_pills.mdx

Added a deprecation warning in each CMS documentation page.

Update CMS documentation

---

docs/fast_data/configuration/secrets_resolution.md
docs/fast_data/runtime_management/control_plane_frontend.mdx

Update fast data runtime management links

edit: update fast data runtime management links

---

docs/release-notes/mia-platform-v13.mdx

fix to doc overview page

---

docusaurus.config.js
static/robots.txt

Fixed the paths to ignore in sitemap and robots.txt file

Fixed path in robots.txt and sitemap

---

docs/console/console-extensibility/locations.md
docs/console/console-extensibility/registration.md

Added: improved extensibility doc adding parametrized entry topic

---

docs/marketplace/add_to_marketplace/contributing_overview.md

fix: wrong URL name

---

.markdownlint.json
docs/console/design-your-projects/sidecars.md
docs/marketplace/add_to_marketplace/add_item_by_type/add_sidecar.md
sidebars.json

Added documentation on how to publish sidecars on Marketplace

feat(IDP-1212): added docs to publish a sidecar resource to the Marketplace via miactl

---

docs/fast_data/data_catalog/overview.md

docs(data-catalog): update details about supported data sources

---

docs/microfrontend-composer/back-kit/60_components/110_crud_export.md
docs/microfrontend-composer/back-kit/60_components/120_crud_export_client.md
versioned_docs/version-11.x.x/business_suite/backoffice/60_components/110_crud_export.md
versioned_docs/version-11.x.x/business_suite/backoffice/60_components/120_crud_export_client.md
versioned_docs/version-12.x.x/microfrontend-composer/back-kit/60_components/110_crud_export.md
versioned_docs/version-12.x.x/microfrontend-composer/back-kit/60_components/120_crud_export_client.md

Fix typo `persistance` -> `persistence`

Fix typo in back-kit doc persistance -> persistence

---

docs/fast_data/concepts/data_loading.mdx

fix: data loading code snippet

---

docs/fast_data/runtime_management/secure_access.md
docs/runtime_suite/projection-storer/10_configuration.md

Fixed link to Fast Data Control Plane application

Fixed link to Fast Data Control Plane application

---

301redirects.json

fix: remove self referencing redirects

---

CONTRIBUTING.md
docs/info/version_policy.md
src/pages/index.js

fix: missing v13 support policy

---

docs/development_suite/api-console/api-design/crud_advanced.md
docs/fast_data/configuration/single_views.md

add generate from data sample for CRUDs and SVs

---

docs/fast_data/runtime_management/workloads.mdx

change controller keyword for state in workloads doc

fix(fast-data): change controller keyword for state in workloads doc

---

docs/release-notes/v13.0.0.md
docs/release-notes/v13.0.1.md
docs/release-notes/versions.md
sidebars.json
versioned_sidebars/version-12.x.x-sidebars.json

RN 13.0.1 to PROD

---

versioned_docs/version-12.x.x/release-notes/v12.3.4.md
versioned_docs/version-12.x.x/release-notes/versions.md
versioned_sidebars/version-12.x.x-sidebars.json

rn v12.3.4

---

docs/marketplace/add_to_marketplace/contributing_overview.md

docs: remarks on marketplace management envs, labels and annotations

---

versioned_docs/version-12.x.x/release-notes/v12.3.4.md

rn-v12.3.4 reordering content

---

versioned_docs/version-12.x.x/release-notes/v12.3.4.md

mini fix on v12.3.4 RN structure

---

docs/release-notes/v13.0.1.md

fix typo in RN v13.0.1

---

docs/release-notes/v13.0.1.md
versioned_docs/version-12.x.x/release-notes/v12.3.4.md

fix typos in RN v13.0.1

---

docs/development_suite/api-console/api-design/merge_collaboration.md

Update the `merge_collaboration.md` page to specify that the merge operation is not a "git merge" and not all the configurations incldued in the repo will be merged.

feat: update merge_collaboration page

---

docs/development_suite/api-console/api-design/listeners.md

feat(IDP-1278): improved listener port documentation

---

docs/infrastructure/self-hosted/self-hosted-requirements.md

This pr provides an update for supported k8s version to 1.30

update k8s supported range

---

docs/development_suite/api-console/api-design/mongo_views.md
docs/release-notes/v13.0.2.md
docs/release-notes/versions.md
sidebars.json

edit RN v13.0.2 hotfix

---

docs/console/project-configuration/manage-environment-variables/manage-environment-variables-with-gitlab.md

Added an info-box referencing the answer of [this discussion](https://github.com/mia-platform/community/discussions/375).

edit: explained the case of multiple secret envs variables

---

docs/console/tutorials/configure-marketplace-components/api-portal.mdx

This pull request aims to update the tutorial about the API Portal documentation

Fix tutorial api portal

---

docs/release-notes/v13.0.3.md

add whitelabeling

---

docs/release-notes/stable versions.md
docs/release-notes/v13.0.1.md
docs/release-notes/v13.0.3.md
docs/release-notes/v13.0.4.md
docs/release-notes/versions.md
sidebars.json
versioned_docs/version-12.x.x/release-notes/v12.3.5.md
versioned_docs/version-12.x.x/release-notes/versions.md
versioned_sidebars/version-12.x.x-sidebars.json

RN v13.0.4 to preview

---

versioned_docs/version-12.x.x/release-notes/v12.3.6.md
versioned_docs/version-12.x.x/release-notes/versions.md
versioned_sidebars/version-12.x.x-sidebars.json

RN-v12.3.6

---

docs/development_suite/deploy/overview.md
docs/development_suite/set-up-infrastructure/enhanced-project-workflow.md
docs/release-notes/v13.0.3.md
docs/release-notes/v13.0.4.md

RN Update v13.0.3 & V13.0.4

---

docs/release-notes/v13.0.5.md

change release date in rn v13.0.5 banner

---

docs/microfrontend-composer/composer/10_structure.md
docs/microfrontend-composer/composer/changelog.md
docs/release-notes/v13.0.5.md
docs/runtime_suite_applications/microfrontend-composer-toolkit/changelog.md

little fix on rn-v13.0.5 content

---

docs/development_suite/api-console/api-design/flow-manager-configurator/overview.md

changed position of link unlink sections in fm-configurator doc

---

docs/info/version_policy.md
docs/release-notes/roadmap.md
docs/release-notes/stable versions.md
docs/release-notes/support-policy.md
docs/release-notes/v13.0.2.md

refactor: improved docs for version policy and support

---

docs/development_suite/api-console/api-design/mongo_views.md

banner for downgrading to crud service v6.X when using views with encryption

---

docs/release-notes/v13.0.5.md
docs/release-notes/v13.0.6.md
docs/release-notes/versions.md
sidebars.json

RN v13.0.6 to Preview

---

docs/development_suite/api-console/api-design/api_key.md

Add warning on wrong or non-existing API Keys

---

docs/console/project-configuration/kustomize-your-configurations/kustomize-use-cases.md

Add HighAvailability example using Kustomize

---

301redirects.json
src/components/LastPages/links.json

Fix redirects and homepage broken link

updare wrong redirect and fix homepage link

---

docs/release-notes/roadmap.md

In this PR we are going to update the Roadmap docs page including new features coming in the next 6 months.

update roadmap docs page

---

docs/getting-started/faqs.md

Add FAQ from GitHub Community

---

docs/infrastructure/self-hosted/installation-chart/helm-values/75_assistant.md

fix: reference to latest llm model for assistant

---

docs/getting-started/faqs.md

update base tag

---

docs/release-notes/v13.1.0.md

feat: update chart helm in v13.1.0 release note

---

docs/release-notes/v13.1.0.md

align main to prod. feat: update chart helm in v13.1.0 release note (#1633)

---

docs/release-notes/v13.1.0.md

Updated Chart Helm version of Console v13.1.0.

fix: update chart name in v13.1.0 release notes

---

docs/release-notes/v13.1.0.md
docs/release-notes/v13.1.1.md
docs/release-notes/versions.md
sidebars.json

edit rn 13.1.1

---

docs/development_suite/api-console/api-design/mongo_views.md

remove warning banner about views with encryption support by crud v7

---

docs/marketplace/tutorials/create-a-rag-application.md

Fix a small typo on the "Create a RAG Application" related to a environment variable name

fix: typo on "Create a RAG Application" tutorial

---

301redirects.json

add a missing redirect for a page renamed in #1404

fix: missing 301 redirect for renamed page

---

docs/release-notes/v13.2.0.md

Edit: updated beta tag for Console Helm Chart

Edit: updated beta tag for Console Helm Chart

---

docs/console/company-configuration/events.mdx

docs: add project to `project_created` event, fix schema

---

docs/data_catalog/compatibility_matrix.md
docs/data_catalog/data_catalog_frontend.mdx

Following the introduction of Bulk Edit functionality, Data Catalog Frontend now uses websockets to communicate with its backend.  
Consequently, this PR add in the Data Catalog section the description of how websocket support can be enabled on the API Gateway.

docs(data-catalog): add documentation regarding websocket support

---

docs/release-notes/v13.2.0.md
docs/release-notes/v13.2.1.md
docs/release-notes/versions.md
sidebars.json

set up rn v13.2.1

---

docs/release-notes/v13.0.7.md
docs/release-notes/versions.md
sidebars.json

release: v13.0.7

---

docs/fast_data/configuration/projection_storer.md
docs/fast_data/faq/fast_data_versioning.md

In this PR is updated the configuration of Projection Storer to describe the support to SSL connection. This includes the description of customizing the certificates/keys supported by the service and how to enable SSL connection within the storage component.

docs(fast-data): describe SSL support in Projection Storer page

---

docs/console/design-your-projects/custom-resources/custom-resources.md
docs/console/design-your-projects/custom-resources/use-cases.md
docs/marketplace/add_to_marketplace/add_item_by_type/add_custom_resource.md

fix: improved CR docs

---

docs/fast_data/configuration/projection_storer.md

This PR improve the description of `castToDate` cast function in the Projection Storer configuration page, clarifying
which it's input and its output.

docs(fast-data): improve description of castToDate function in projection storer page

---

301redirects.json
docs/data_catalog/compatibility_matrix.md
docs/data_catalog/data_catalog_agent_setup.mdx
docs/data_catalog/data_catalog_frontend.mdx
docs/data_catalog/data_catalog_open_lineage.mdx
docs/data_catalog/database_setup.mdx
docs/fast_data/runtime_management/compatibility_matrix.md
docs/fast_data/runtime_management/database_setup.mdx

This PR describes the sync step of data catalog configuration.

docs(data-catalog): add sync to data-catalog

---

301redirects.json

Update redirect for cast functions page.

fix: update redirect to cast functions page

---

docs/console/design-your-projects/custom-resources/custom-resources.md
docs/development_suite/api-console/api-design/services.md
docs/marketplace/add_to_marketplace/create_your_company_marketplace.md

Removed references to "Marketplace Notification" feature preview, since notification will always be available.

fix: removed references to Marketplace Notification feature preview

---

docs/release-notes/v13.3.0.md
sidebars.json

added chart helm on v13.3.0

---

docs/development_suite/api-console/advanced-section/api-gateway-envoy/udp.md
sidebars.json

add new page udp

---

docs/release-notes/v13.0.8.md
docs/release-notes/versions.md
sidebars.json

edit RN v13.0.8

---

docs/development_suite/monitoring/resources/custom-resources.md

fix: Custom Resources slug pointed to wrong page

---

docs/microfrontend-composer/external-components/bundling.md
docs/microfrontend-composer/external-components/manifest.md
docs/microfrontend-composer/external-components/overview.md

Improved documentation on MFE Composer Components Explorer

Added documentation on components explorer

---

docs/development_suite/monitoring/resources/custom-resources.md

scratch_info

---

docs/runtime_suite/http-proxy-manager/30_configuration.md
docs/runtime_suite/http-proxy-manager/changelog.md

chore(docs): update HTTP Proxy Manager documentation

---

docs/console/company-configuration/events.mdx

doc: configuration saved webhook

---

docs/runtime_suite/audit-trail/_category_.json

fix(Audit Trail): add missing _category_.json

---

docs/development_suite/api-console/api-design/fine-grained-access-control.md
sidebars.json

Small improvements to the Design Fine-Grained Access Control feature.
I've also moved the position in the sidebar to avoid it being in the middle of other unrelated docs

fix: design fine grained access control docs

---

docs/console/company-configuration/clusters-management/cluster-setup.mdx
docs/console/design-your-projects/custom-resources/custom-resources.md

update: added information

---

docs/release-notes/v13.4.0.md

This PR simply references a different chart helm for v13.4.0 (new chart: v13.8.0-beta.1)

fix: update chart referenced in v13.4.0

---

docs/release-notes/v13.4.0.md

This PR changes the release not for Console version `13.4.0` referencing a different Helm chart version and adding a new fix

Updated release note

---

docs/release-notes/v13.5.0.md

updated chart helm on RN 13.5.0

---

docs/release-notes/v13.1.3.md
docs/release-notes/v13.3.1.md
docs/release-notes/v13.5.0.md
docs/release-notes/versions.md
sidebars.json

This PR includes the following changes:
- update release note of Console `v13.5.0` to set the latest Helm Chart version
- add release note page for Console `v13.3.1`
- add release note page for Console `v13.1.3`

docs(release-note): update release note of v13.5.0, v13.3.1 and v13.1.3

---

static/schemas/data-fabric-control-plane.config.schema.json

add settings key in control plane config map example

fix: add settings key in cp cm example

---

docs/release-notes/v13.5.0.md

Updated release notes to include a new CRUD SQL plugin in the Marketplace

Add CRUD SQL plugin to RN

---

docs/data_catalog/data_catalog_fabric_bff.mdx
docs/data_catalog/data_catalog_job_runner.mdx
docs/data_catalog/data_catalog_open_lineage.mdx
docs/data_catalog/secure_access.mdx

This MR fixes some routes that were wrongly listed in the Data Catalog microservices

fix(data-catalog): endpoint and routes definitions

---

docs/release-notes/v13.1.0.md
docs/release-notes/v13.1.1.md
docs/release-notes/v13.1.2.md
docs/release-notes/v13.1.3.md
docs/release-notes/v13.1.4.md
docs/release-notes/v13.3.0.md
docs/release-notes/v13.3.1.md
docs/release-notes/v13.3.2.md
docs/release-notes/v13.5.0.md
docs/release-notes/versions.md
sidebars.json

rn: for gitlab fix breaking backporting on v13.1 and v13.3

---

docs/console/company-configuration/clusters-management/connect-and-manage-cluster.mdx
docs/console/company-configuration/providers/api-reference.md
docs/console/company-configuration/providers/configure-provider.mdx

Added new credentials for Azure DevOps

update: azure credentials page

---

301redirects.json

Add redirects of the old crud-sql plugin docs.

redirect old crud-postgresql links

---

docs/release-notes/stable versions.md
docs/release-notes/v13.3.3.md
docs/release-notes/v13.5.1.md
docs/release-notes/v13.5.2.md
docs/release-notes/versions.md
sidebars.json

setup release notes

---

docs/release-notes/v13.3.3.md
docs/release-notes/v13.3.4.md
docs/release-notes/v13.5.2.md
docs/release-notes/versions.md
sidebars.json

Insert RN v13.3.4

---

docs/console/videos/custom-frontend-iframe.mdx
docs/console/videos/mia-assistant.mdx
docs/console/videos/providers-in-console.mdx
docs/console/videos/subtitle/custom-frontend-iframe.json
docs/console/videos/subtitle/mia-assistant.json
docs/console/videos/subtitle/providers-in-console.json
scripts/parse-subtitle.js
sidebars.json
video_subtitle/[BZ6JNF7HZe4]mia_assistant.srt
video_subtitle/[KApjZrvQ8cU]custom_frontend_iframe.srt
video_subtitle/[c2J8xdLT-LI]providers_in_console.srt

Add new video pages and fix the script to divide subtitle.

Add/video 13.5

---

docs/release-notes/v13.3.5.md
docs/release-notes/versions.md
sidebars.json

Insert rn v13.3.5

---

docs/release-notes/v13.3.5.md
docs/release-notes/versions.md
sidebars.json

* Create v13.3.5.md
* Update versions.md
* Update sidebars.json
* Update docs/release-notes/versions.md
* Update docs/release-notes/v13.3.5.md
---------

align rn v13.3.5 from prod to main 

---

docs/runtime_suite/crud-sql/30_how_to_use.md

chore(docs): update CRUD SQL documentation

---

docs/fast_data/runtime_management/compatibility_matrix.md

docs(fast-data): update compatibility-matrix of runtime management

---

docs/data_catalog/compatibility_matrix.md

Update compatibility_matrix for Data Catalog

---

docs/release-notes/v13.6.0.md

added import kubernetes via miactl feature

---

.cspell.json
docs/cli/miactl/20_setup.md
docs/cli/miactl/30_commands.md
docs/cli/miactl/40_examples.md
docs/cli/miactl/changelog.md
docs/release-notes/v13.6.0.md

RN from main to prod

---

docs/development_suite/identity-and-access-management/console-levels-and-permission-management.md

edit permission

---

docs/runtime_suite_applications/api-documentation-aggregator/30_faqs.md

Reverts mia-platform/documentation#1988

Revert "chore(docs): update API Documentation Aggregator documentation"

---

docs/release-notes/v13.6.0.md
docs/release-notes/v13.6.1.md
docs/release-notes/versions.md
sidebars.json

set up rn v13.6.1

---

docs/release-notes/v13.6.1.md

removed improvement miactl on RN v13.6.1

---

docs/release-notes/v13.6.0.md

updated: docs to change the stable version

---

docs/release-notes/v13.6.1.md

update: 13.6.1 release note with chart helm to v13.10.1

---

docs/release-notes/v13.6.0.md
docs/release-notes/v13.6.1.md
docs/release-notes/v13.6.2.md
docs/release-notes/versions.md
sidebars.json

set up rn 13.6.2 to preview

---

docs/development_suite/api-console/api-design/services.md
docs/release-notes/v13.6.2.md

added cursor AI to RN and docs

---

docs/development_suite/api-console/api-design/services.md

The PR add the new service account section for a new micro service

docs: add service account section in design

---

docs/release-notes/v13.7.0.md

Add docs link for Integration Connector Agent in RN v13.7.0

---

docs/release-notes/v13.7.1.md

fixed rn preview v13.7.1

---

docs/marketplace/compatibility_matrices/mongo_compatibility_matrix.md

Add files-service mongo 7 compatbility

---

versioned_docs/version-13.x.x/release-notes/v13.7.2.md
versioned_docs/version-13.x.x/release-notes/versions.md
versioned_sidebars/version-13.x.x-sidebars.json

RN for the 13.7.2 hotfix release

rn: hotfix v13.7.2

---

docs/software-catalog/basic-concepts/10_items-types.md
docs/software-catalog/items-manifest/infrastructure-component-runtime.md

edited infra component runtime item on software catalog

---

docs/release-notes/mia-platform-v14.mdx
docs/release-notes/v14.0.0.mdx

Add the following marketplace updates to the v14 release notes:
- Teleconsultation Service BE

Mia Care Marketplace Updates for v14 release notes

---

docs/release-notes/v14.0.0.mdx

Update release note with composability news

update comp rn

---

docs/marketplace/compatibility_matrices/mongo_compatibility_matrix.md

added MongoDB Server v8.0 to MongoDB Compatibility Matrix

---

versioned_docs/version-13.x.x/release-notes/v13.7.3.md
versioned_docs/version-13.x.x/release-notes/versions.md
versioned_sidebars/version-13.x.x-sidebars.json

RN for the 13.7.3 hotfix release

rn: hotfix v13.7.3

---

docs/release-notes/v14.0.0.mdx
docusaurus.config.js
src/pages/index.js

removed preview banner to v14 RN

---

docs/infrastructure/self-hosted/self-hosted-requirements.md

docs from main to prod

---

versioned_docs/version-13.x.x/release-notes/v13.7.4.md

added: new 13.7.4 release

---

docs/marketplace/overview_marketplace.md

feat: add how to edit mia-platform catalog items

---

301redirects.json

update rag tutorial redirect

---

src/components/HomePage/HomePageComponent.css
src/components/HomePage/HomePageComponent.jsx

add background color to hero section

---

src/components/HomePage/HomePageComponent.jsx

Just a fix for light mode search bar

fix on search bar to light mode

---

check-content.js
docs/console/tutorials/create-extension-with-sso.md
scripts/validate-links.js
sidebars.json

This PR add a tutorial on how to create your own iframe extension and secure them with console SSO

Add extension SSO tutorial

---

versioned_docs/version-13.x.x/release-notes/v13.7.5.md
versioned_docs/version-13.x.x/release-notes/versions.md

fix: v13.7.5 release note name

---

docs/fast_data/configuration/single_view_creator/plugin.md

fast data read from multiple databases add little changes to code example

---

docs/marketplace/compatibility_matrices/mongo_compatibility_matrix.md

feat: update MongoDB Compatibility Matrix with up-to-date services

---

docs/software-catalog/items-management/overview.md
docs/software-catalog/items-manifest/overview.md

Move permissions section to items management

Move permissions section to items management

---

docs/infrastructure/self-hosted/self-hosted-requirements.md

Changed the requirements of MongoDB from enterprise to Community

(fix) mongodb community requirement

---

nginx/website.conf

include gfont

---

docusaurus.config.js
package.json
yarn.lock

restore mermaid

---

docs/products/console/cli/miactl/changelog.md
docs/runtime-components/tools/mlp/20_setup.md
docs/runtime-components/tools/mlp/changelog.md

Update files for mlp and miactl

docs: update clis pages

---

docs/products/console/tutorials/create-extension-with-sso.md

add go specification to the code block

add go to the code block

---

docs/infrastructure/self-hosted/self-hosted-requirements.md

added AKV as secret manager

---

docs/products/console/mcp/mcp-server/20_setup.md

This PR includes a small fix on the suggestions on how to run the MPC Server in VS Code client.
It also fix the note area from the `:::note` template to the `> **_Note:_**`.

fix: correct template and examples in MCP configuration
